const catalogo =[
    {
      id: 1,
      name: "Bicicleta MTB Trek X-Caliber 8",
      image: "https://example.com/bike_images/trek_xcaliber8.jpg",
      price: 1349.99,
      category: "MTB",
      brand: "Trek",
      stock: 10,
    },
    {
      id: 2,
      name: "Bicicleta de Pista Fuji Track Pro",
      image: "https://example.com/bike_images/fuji_track_pro.jpg",
      price: 1799.99,
      category: "Pista",
      brand: "Fuji",
      stock: 10,
    },
    {
      id: 3,
      name: "Bicicleta MTB Giant Talon 29er",
      image: "https://example.com/bike_images/giant_talon_29er.jpg",
      price: 899.99,
      category: "MTB",
      brand: "Giant",
      stock: 10,
    },
    {
      id: 4,
      name: "Bicicleta de Pista Specialized Langster",
      image: "https://example.com/bike_images/specialized_langster.jpg",
      price: 1099.99,
      category: "Pista",
      brand: "Specialized",
      stock: 10,
    },
    {
      id: 5,
      name: "Bicicleta MTB Santa Cruz 5010",
      image: "https://example.com/bike_images/santa_cruz_5010.jpg",
      price: 3299.99,
      category: "MTB",
      brand: "Santa Cruz",
      stock: 10,
    },
    {
      id:6,
      name: "Bicicleta de Pista Bianchi Pista",
      image: "https://example.com/bike_images/bianchi_pista.jpg",
      price: 899.99,
      category: "Pista",
      brand: "Bianchi",
      stock: 10,
    },
    {
      id: 7,
      name: "Bicicleta MTB Scott Scale 970",
      image: "https://example.com/bike_images/scott_scale_970.jpg",
      price: 1199.99,
      category: "MTB",
      brand: "Scott",
      stock: 10,
    },
    {
      id: 8,
      name: "Bicicleta de Pista Cinelli Mash Work",
      image: "https://example.com/bike_images/cinelli_mash_work.jpg",
      price: 1299.99,
      category: "Pista",
      brand: "Cinelli",
      stock: 10,
    },
    {
      id: 9,
      name: "Bicicleta MTB Yeti SB130",
      image: "https://example.com/bike_images/yeti_sb130.jpg",
      price: 5999.99,
      category: "MTB",
      brand: "Yeti",
      stock: 10,
    },
    {
      id: 10,
      name: "Bicicleta de Pista All-City Thunderdome",
      image: "https://example.com/bike_images/allcity_thunderdome.jpg",
      price: 1199.99,
      category: "Pista",
      brand: "All-City",
      stock: 10,
    }
    ];  

    export default catalogo;